language: node_js

node_js:
- "lts/*"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules
    - packages/react-schema/node_modules
    - packages/react-schema-form/node_modules
    - packages/validation/node_modules

install:
  - npm install
  - yarn bootstrap

script:
  - yarn lint
  - yarn test

deploy:
  provider: script
  script: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && npm run publish:npm
  on:
    tags: true
